### ISSUE TITLE
Sorting and filtering on autonumber field is not possible

### ISSUE THREAD

**Issue by tmisker** [mendixlabs/list-view-controls#14]
When using the 'Header sort' widget, it is not possible to sort on autonumbers.
Also, filtering using the 'Text box search' is not possible with autonumbers.

**Comment by Andries-Smit** [comment]
Good point! We will add to the feature list. 

I don't think there is technical limitation. For now you can hack it yourself by editing the xml 
`HeaderSort.xml` inside the mpk (zipped)

Just add to the list:
``` xml
<attributeType name="AutoNumber"/>
```
https://github.com/mendixlabs/list-view-controls/blob/master/src/HeaderSort/HeaderSort.xml#L23

**Comment by tmisker** [comment]
Just to confirm: it works!

**Comment by edwinmp** [comment]
Hi Tim, this has been added in the app store version 1.2.0.
