### ISSUE TITLE
Discrepancy between the widget in Appstore and sample project

### ISSUE THREAD

**Issue by LexvanRooy** [mendixlabs/list-view-controls#15]
1) documentation in Appstore is full of broken links
2) Why is the sample project showing a lot more options as the actual widget??  very confusing

**Comment by Andries-Smit** [comment]
Dear Lex

The sample project is our development project, we are current adding new feature, released soon.

If you would like to use the sample project use it one that is attached to the latest release.
https://github.com/mendixlabs/list-view-controls/releases/latest

Also the broken links will be fix in the next release

Cheers,
Andries

**Comment by LexvanRooy** [comment]
ahh... well that explains a lot..... :-)
anxiously awaiting a newer build then

Op vr 11 mei 2018 20:14 schreef Andries Smit <notifications@github.com>:
