### ISSUE TITLE
Dates not supported by TextBoxSearch widget

### ISSUE THREAD

**Issue by mchmx** [mendixlabs/list-view-controls#17]
When a date attribute is selected as the target of TextBoxSearch, the widget throws an error. The required conversion from a string to a date doesn't seem to be in place.

**Comment by Andries-Smit** [comment]
Date were not support though it was possible to select them. We will look into adding support for them.

**Comment by Andries-Smit** [comment]
There is not easy solution to this. we will remove te option to select a data as an attribute.
