### ISSUE TITLE
When using Drop Down Filter widget, list view sort is disabled

### ISSUE THREAD

**Issue by lambatross** [mendixlabs/list-view-controls#19]
We were trying to use the Drop Down Filter widget for a list view with the sorting built into the list view, but the sorting selected has been disabled. (no sort is applied when using the filter alone)

I see that using the drop down sort with the filter will allow the list view to be sorted. But, this does not address two specific scenarios:
-When we do no wish to allow the sorting to be changed by a user.
-When there needs to be a secondary or tertiary sort on top of the primary sort.

**Comment by Andries-Smit** [comment]
Fixed and release  v1.2.1 
https://appstore.home.mendix.com/link/app/105694/
