### ISSUE TITLE
Using the Check-box filter widget dynamically within a context object

### ISSUE THREAD

**Issue by allardbrand** [mendixlabs/list-view-controls#2]
Hi team,

Thank you for this amazing widget, great addition to the Mendix platform!

I am trying to set-up the Check-box filter widget in such a way, that I can filter a list view with 'Plants' on basis on the 'Country' this plant is located. However, I would like to create/use these filters dynamically. Is this possible? 

I'm currently using the following set-up:

![image](https://user-images.githubusercontent.com/4025933/33318265-6081db40-d43a-11e7-980e-b2550e5915f0.png)

I configured the widget to filter by XPath, using the following XPath constraint [Project.Plant_Country = '[%CurrentObject%]']. When I test this configuration, I get the following error: 

Project.Plant_Overview.check_boxFilter1 : Requires a context object

Am I doing something wrong? Or is the use of this widget within a context object not (yet) supported? Thank you in advance for your reply!

**Comment by Andries-Smit** [comment]
Dear Allard,

All list view controls should be placed outside the list view. Place them at the location where you expect them to be rendered.

![image](https://user-images.githubusercontent.com/6724749/33927572-1dd8e0ae-dfe3-11e7-87c8-701b7e7fa0e2.png)

The controls can work with a context if need be; see sample below.
Note an xpath is using a  '[%CurrentObject%]' is will show an error when there is no context at all.

![image](https://user-images.githubusercontent.com/6724749/33928187-4c3794d4-dfe5-11e7-8c76-91a7b90d313d.png)

Cheers, Andries
