### ISSUE TITLE
Problems when trying to build this locally

### ISSUE THREAD

**Issue by gajduk** [mendixlabs/list-view-controls#24]
I followed the instructions from the readme:

```
> npm install 
> npm start
> 
```

I get confronted by a

```
Error in "webpack" module, webpack-dev-server not found
```

Followed after some lines by
```
 "Property 'value' does not exist on type 'Readonly<{}>'" in TextBoxFilter.specs.ts
```

**Comment by SamuelMuloki** [comment]
Hello Andrej, i was not able to reproduce your issue, could you please share a screenshot showing the error and steps to reproduce the issue 
Cheers
Samuel

**Comment by Andries-Smit** [comment]
Closed, no response
