### ISSUE TITLE
Search criteria erased after returning to the form from another (details) form

### ISSUE THREAD

**Issue by veldkampe** [mendixlabs/list-view-controls#26]
The search criteria used are erased after returning to the form from another (details) form, but the search criteria are still applied to the grid. Is it possible to show the applied search criteria?

**Comment by Andries-Smit** [comment]
Dear Erik,

The feature to memorize the settings could not be implemented with the current Mendix client.

We will discuss this issue with the product owner and will get back to you.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Hi Erik,

We planned the enhancement, though we depend on a small change in the Mendix modeler. I will keep you posted on our plans.

Cheers, Andries

**Comment by Andries-Smit** [comment]
Dear Erik,

We completed the persisting state and released it as v1.3.0 in the app store.
https://appstore.home.mendix.com/link/app/105694/

Cheers,
Andries
