### ISSUE TITLE
Enumeration not selectable as drop down filter attribute

### ISSUE THREAD

**Issue by kesslera** [mendixlabs/list-view-controls#29]
Hi MxTeam, 
is there a special reason, why enumeration attributes are not allowed as drop down filter option? 
I have to do a workaround and use Xpath as option and add the sorting constraint manually. 
It would be much more comfortable, if we could just select the enumeration as attribute and the rest is done automatically (similar to adding an enumeration filter on data grids and template grids)

Best regards,
Alex

**Comment by djkwagala** [comment]
Hello Alexander,
Thanks for reporting this issue. We are working on an upcoming release for the list-view-controls hopefully this issue will be fixed in that release.

Regards
Derrick
