### ISSUE TITLE
Idea: Checkbox Filter OR instead of AND

### ISSUE THREAD

**Issue by melvingrootenboers** [mendixlabs/list-view-controls#3]
I would like to use multiple checkbox filters with an OR operration
![image](https://user-images.githubusercontent.com/10810429/33706323-0feb152e-db34-11e7-853b-daed9d661f7f.png)

**Comment by Andries-Smit** [comment]
Hi Melvin,

Great idea, let put it forward to the product manager. We are planning the extend the list view controles next year, this would definitely be a candidate. 

Cheers, Andries

**Comment by Andries-Smit** [comment]
Good news, your requested change is now on or road map.

**Comment by Andries-Smit** [comment]
Feature implemented and release 1.1.0 https://appstore.home.mendix.com/link/app/105694/
