### ISSUE TITLE
Dropdown-Dynamic: Empty caption not showed when multi select

### ISSUE THREAD

**Issue by ssuijkerbuijk** [mendixlabs/list-view-controls#31]
Empty caption isn't showed in the box when Multi-select is true. Would be nice to show it just like when Multi-select is false. This way we can eliminate the labels for the filters.

**Comment by jseremba** [comment]
Thank you @ssuijkerbuijk for reporting this issue, we will look into it and get back to you as soon as possible.

Regards 
Joseph

**Comment by jseremba** [comment]
Dear @ssuijkerbuijk 
Thanks for reporting this issue, we would very much love to fix it, however we are having trouble in reproducing it, could you please provide us with a testable project with the issue or steps to follow to reproduce.

**Comment by Andries-Smit** [comment]
No sample is provided. Please reopen the issue with a sample project if this issue is still relevant

**Comment by ssuijkerbuijk** [comment]
Sorry for the delayed reaction, but I have confused two widgets. Did not add the widgets myself to the project and thought that "drop down - dynamic" widget was from the list view controls. Bu tnow i see it's from the grid search widget....
