### ISSUE TITLE
List resets when using dropdown - Dynamic on the same page.

### ISSUE THREAD

**Issue by ssuijkerbuijk** [mendixlabs/list-view-controls#36]
When using the default mendix list search (or the "Text box search" in this widget, same behavior) on the same page as Dropdown - Dynamic with multiselect on, the list search results are reset on clicking a list item. 

Steps to reproduce:
- Open a page with a list (search on, on click action) and the widget drop down dynamic.
- Start searching by just typing in the seearchword. Dont use ENTER.
- Click on a search item.

Result:
Search is reset and onclick action is not fired. Instead of clicking a list item, you can click anywhere in the screen with the same result. WHen you do a new search after the reset, the list will not reset anymore. 

Extra: Also pressing ENTER after typing a searchword will reset the list. 

Mendix version 7.18.1

**Comment by ssuijkerbuijk** [comment]
When multiselect of, everyhthing is working fine.

**Comment by ssuijkerbuijk** [comment]
Sorry for the delayed reaction, but I have confused two widgets. Did not add the widgets myself to the project and thought that "drop down - dynamic" widget was from the "list view controls". But now i see it's from the "grid search" widget.... So i changed the text box search to "Multifield" from the "grid search" widget and know everything works fine. So the problem is that those two widget bundles ("list view controls" and "grid search" (also by Mendix)) are not working together which causes the error. 

It still would be nice if we can use both widget bundles together beacause i now have a problem with sorting the list via the headers with the widget "Header sort" form "list view controls" in combination with the widgets "multifield" and "drop down - dynamic" from the "grid search" bundle...

**Comment by Andries-Smit** [comment]
Hi Sander, those widget are not build by the same team. We will have a look at them and see if we can combine the effort. Cheers.

Ref: https://appstore.home.mendix.com/link/app/49364/
