### ISSUE TITLE
Widgets in list view control not listening to eachother

### ISSUE THREAD

**Issue by ssuijkerbuijk** [mendixlabs/list-view-controls#37]
For example:
Widgets drop down - dynamic and textbox search are not listening to each other. When using both on one page, the list is only filtered by the last used filter, not by both. This will result in text box search results in the list which are not valid for the drop down - dynamic filtering.

**Comment by Andries-Smit** [comment]
Hi Sander, 

Thanks for reporting this issue. I will have a look at it in the new year.

Cheers, Andries

**Comment by ssuijkerbuijk** [comment]
Sorry for the delayed reaction, but I have confused two widgets. Did not add the widgets myself to the project and thought that "drop down - dynamic" widget was from the "list view controls". But now i see it's from the "grid search" widget.... So i changed the text box search to "Multifield" from the "grid search" widget and know everything works fine. So the problem is that those two widget bundles ("list view controls" and "grid search" (also by Mendix)) are not working together which causes the error. 

It still would be nice if we can use both widget bundles together beacause i now have a problem with sorting the list via the headers with the widget "Header sort" form "list view controls" in combination with the widgets "multifield" and "drop down - dynamic" from the "grid search" bundle...

**Comment by Andries-Smit** [comment]
Hi  Sander, those widget are not build by the same team. We will have a look at them and see if we can combine the effort. Cheers.

Ref: https://appstore.home.mendix.com/link/app/49364/
