### ISSUE TITLE
Update (v1.3.0) to be compatible with Mx v. 7.22.1

### ISSUE THREAD

**Issue by rickyv3** [mendixlabs/list-view-controls#38]
Hi @Andries-Smit ,

Do you guys know when you plan to update v1.3.0 to be compatible with Mx 7.22.1?

Initial sort for the header widget does not work.

Thank you!

**Comment by rickyv3** [comment]
The header sort widget continually fails in our project. We cannot consistently repeat the issue, but here's an example screenshot. No errors are logged in the console, other than the message that the list view controls are not compatible with this version of the modeler. Once you refresh the page, the header widget locates the list view and the issue resolves itself. 

![ListViewIssue](https://user-images.githubusercontent.com/13573078/54280304-2669eb80-4565-11e9-8d57-3974d7fa7d49.png)

**Comment by Andries-Smit** [comment]
Hi Rick,

The `Grid Search` widgets can NOT be used in combination with the list view control widget on the same List view. Is this your case?

if not a sample project might be helpfull.

thanks you, Andries

**Comment by rickyv3** [comment]
Hi Andries,

That was indeed the case, but we worked with Eric Tieniber (author of grid search) to make grid search place nice with the list view controls. This issue also persists on pages where we do not use grid search controls. 

Unfortunately, I cannot seem to recreate this in a test project. Eric has access to our project and is going to take a look. We do see an error in the modeler console letting us know that the list view controls are not compatible with our version of mx. I'll report back with Eric's findings.

**Comment by Andries-Smit** [comment]
Hi Rick,

The fix from Eric is now available in version v1.3.1 in the app store https://appstore.home.mendix.com/link/app/105694/

Cheers, Andries
