### ISSUE TITLE
Refresh with pagination goes back to page 1

### ISSUE THREAD

**Issue by PappasFreetas** [mendixlabs/list-view-controls#39]
We have a list view with pagination that has a button that can delete an object in the list. Upon delete if we refresh the listView ends up going back to page 1 which can be frustrating if a user has gone through many pages.

**Comment by Andries-Smit** [comment]
Dear  ....

We have a test case around this behaviour. We stated that if the last item of the page is deleted it will go to the first page. Is this the case you describe?  If an other item is removed it should stay on the same page. You could test this at https://listviewcontrols.mxapps.io/p/playground 

Could you please provide us with some more information when it fails in your situation? A demo demo test project would be helpful

Cheers, Andries

**Comment by Andries-Smit** [comment]
Issue will be closed - No test project was provided. If this issue still persists, please contact https://support.mendix.com create a new ticket with a simplified test case.
