### ISSUE TITLE
Issues running development environment for personalized changes

### ISSUE THREAD

**Issue by aleworth** [mendixlabs/list-view-controls#42]
I am unable to create a stable environment to edit this project in. I've gone through and installed all prerequisites listed in the README file within the project. I've gone through the different steps and I am unable to actually build the new application. I believe I've properly made the changes I need to to the code, but it doesn't matter because I'm not able to compile it and test it.

Please provide a more detailed step-by-step description of how to prepare an operable development environment to work on this project.

Thank you

(Modeler 7.22.1, using cmd and/or Ubuntu Bash to download necessary prereqs.)
Finally tried to use the `yo mendix` command in cmd, now I'm getting a 404 error for the two widgets that are being used in the app.

Updates:
(3/15/19)
I was able to get things working up to the `npm start` point. The browser opens, the project attempts to run, and then I receive new errors with the code TS2722: Cannot invoke an object which is possibly 'undefined'. With reference to the file: /src/Pagination/components/__tests__/Pagination.spec.ts(113, 13)

Now going to be working through that.

(3/15/19 - End of Day)
Dipped into the tsconfig.json file and changed the "strict" attribute to false on line 19. The project finally compiled correctly without errors after that. Now I'm running into an issue actually testing it, after entering npm start and the project compiling correctly I get a new error:
[HPM] Error occurred while trying to proxy request / from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

[HPM] Error occurred while trying to proxy request /favicon.ico from localhost:3000 to http://localhost:8080 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

So maybe a goal for next week at this point.

**Comment by Andries-Smit** [comment]
For you information:
- The development could work on a windows machene, no need for Ubunto bash
- The `yo mendix` could not be used for existing widgets... it only for scaffolding new ones
- the `npm start` will proxy all request to port http://localhost:8080 except for the development files. So please make sure you have the mendix test project running on the that URL else you will get a connection error
 you can change the URL in the webpack.config.js or even better via the command
> npm config set list-view-controls:mendixhost http://host:port
- not sure where the .spec.ts error is comming from. Though for development you can disable the "strict" if you like

Please keep us informed

**Comment by Andries-Smit** [comment]
Issue is closed due to no response. If this issue still persists, please contact https://support.mendix.com create a new ticket with a simplified test case.
