### ISSUE TITLE
Header sort initial sort doesn't work within snippet

### ISSUE THREAD

**Issue by lisavandeput** [mendixlabs/list-view-controls#43]
We used de header sort in a snippet to use on multiple pages, but it appears the initial sort on a header sort doesn't work from a snippet. The rest is working fine.

**Comment by Andries-Smit** [comment]
Dear Lisa, 

What is in the snippet; the sort and or list view?

Could you please share a screenshot or a test case? 

Cheers, Andries

**Comment by Andries-Smit** [comment]
Dear Lisa, 

Please re-validate the issue the latest release v1.3.1 https://appstore.home.mendix.com/link/app/105694/

We are looking forward to your response

Cheers, Andries

**Comment by lisavandeput** [comment]
Dear Andries,

In the snippet is only the sort (see screenshot). When the page is loaded, the initial sort doesn't work. When put on the same page as the listview, it works.

![Screenshot listviewsort](https://user-images.githubusercontent.com/36765121/55618654-5d63a380-5797-11e9-9841-91ae5764b3cd.jpg)

**Comment by Thony1973** [comment]
@Andries-Smit, the initial sort of Header Sort is not working in 7.23.3. Do you know when this is solved?

**Comment by Andries-Smit** [comment]
Issue will be closed - No test project was provided. If this issue still persists, please contact https://support.mendix.com create a new ticket with a simplified test case.
