### ISSUE TITLE
Primary MD Has A Bad Link

### ISSUE THREAD

**Issue by keithnicholson** [mendixlabs/list-view-controls#52]
The MD - https://github.com/mendixlabs/list-view-controls/blob/master/README.md has a bad link for the Header Sort.  Please see the link 

`Please follow Header sort guide `

It goes nowhere.

**Comment by Andries-Smit** [comment]
Thanks for reporting, we merged documentation... but forgotten this one. We will restore it.

**Comment by Andries-Smit** [comment]
Fixed in v1.3.4
