### ISSUE TITLE
Searching data with empty attributes

### ISSUE THREAD

**Issue by joelvdgraaf** [mendixlabs/list-view-controls#6]
Each search widget is used in the XPath even when input field is emtpy. The following XPath is created: 
//Relaties.Contactpersoon[contains(NaamVolledig,'')][contains(Email,'')][contains(Telefoon,'') or contains(Mobiel,'')][contains(Kenmerken,'')][Actief = 'true']

The attribute 'Kenmerken' is for some data empty and therefor the data automatically excluded from the resultlist. '' is something else than empty.

Please fix the widget for only searching when the input field contains data, otherwise skip the constraint.

**Comment by djkwagala** [comment]
@joelvdgraaf thanks for this feedback. We'll get back to you on this.

**Comment by Andries-Smit** [comment]
Thank you for your feedback. The request change is now on or road map.

**Comment by rickyv3** [comment]
Hey @Andries-Smit , do you guys have a timeline for when you expect to have this issue resolved?

**Comment by Andries-Smit** [comment]
Solution implemented and release 1.1.0 https://appstore.home.mendix.com/link/app/105694/
