### ISSUE TITLE
Can the DropDownFilter also retrieve all attribute values and apply dynamically?

### ISSUE THREAD

**Issue by Vilscon** [mendixlabs/list-view-controls#8]
I want to filter on the Homework attribute 'subject'. These subjects can be changed over time. Therefor I want the list to filter upon to grow dynamically, instead of a fixed set of values. Is it possible (with this or any other plugin) to only select an entity attribute to filter on and the Dropdown will retrieve all possible values and fill the dropdown list?

Would save human errors as well, when forgetting a certain attribute value :)

**Comment by Andries-Smit** [comment]
Dear Vilscon,

The requested feature is not possible with the current filters, and is not planned at the moment.

I would recommend to build your own filter structure with standard Mendix components. Create a (filter) entity, with a data view that contains a drop down of you subjects. Place a list view in the dataview with a data source microflow. The microflow can take in account al filters that the users have selected and return the expected list

Cheers,
Andries

**Comment by macrel** [comment]
This is a huge lack IMO. Great widget, but please make it possible to create dropdown filters filled by association. Tons of usecases for this. Example: order listview with status filter (status is fixed list which the user can configure with maybe 5 statusses, dropdown would be way better UX then text search).
