### ISSUE TITLE
Pagination doesn't refresh when needed

### ISSUE THREAD

**Issue by lrporder** [mendixlabs/list-view-controls#9]
Pagination added on listview with page size x.  Hide unused paging = yes. When there are up to exactly x items, pagination is not shown. Ok. Now add an item with refresh in client, so total sum of items is x+1 and a second page is needed. Pagination doesn't show up. Refresh page in browser and pagination is shown with one item on second page. So it does hide unused paging, but it doesn't show immediately when paging becomes needed. Also it doesn't hide when you remove items until the total sum reaches x, but that's less of an issue.

**Comment by djkwagala** [comment]
Hi @lrporder,
Thanks for providing this useful feedback. The issue has been resolved and will be included in the coming release of this widget. In the meantime [here](https://github.com/FlockOfBirds/list-view-controls/releases/tag/v1.1.2-beta1) is a usable beta-version with the fix.

**Comment by lrporder** [comment]
Fix confirmed. Thanks!

**Comment by Andries-Smit** [comment]
This issue is resolved in the app store release V1.1.2 
https://appstore.home.mendix.com/link/app/105694/
